backend:
  name: git-gateway # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master # Branch to update
  repo: vagr9k/gatsby-advanced-starter # Repo for pushing new commits. Make sure to replace with your repo!
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: "Post"
    folder: "content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "SEO Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: settings
    label: Settings
    files:
      - name: headerNavigationLinks
        label: Header Links
        file: "data/navigationLinks.json"
        fields:
          - label: Links
            name: headers
            required: true
            widget: list
            minimize_collapsed: true
            fields:
              - { label: "title", name: "title", widget: "string" }
              - { label: "link", name: "link", widget: "string" }
      - name: general
        label: General
        file: "data/site.json"
        fields:
          - label: Site Title
            name: siteTitle
            widget: string
            required: true
          - label: Site Title Short
            name: siteTitleShort
            widget: string
            required: true
          - label: Site Description
            name: siteDescription
            widget: string
            required: true
          - label: Logo
            name: siteLogo
            widget: image
            default: "/logos/logo-1024.png"
          - label: Site Url
            name: siteUrl
            widget: string
            required: true
          - label: Path Prefix
            name: pathPrefix
            widget: string
            required: true
          - label: Site RSS Title
            name: siteRssTitle
            widget: string
            required: true
          - label: siteFBAppID
            name: siteFBAppID
            widget: string
            required: true
          - label: googleAnalyticsID
            name: googleAnalyticsID
            widget: string
            required: true
          - label: disqusShortname
            name: disqusShortname
            widget: string
            required: true
          - label: dateFromFormat
            name: dateFromFormat
            widget: string
            required: true
          - label: dateFormat
            name: dateFormat
            widget: string
            required: true
          - label: postsPerPage
            name: postsPerPage
            widget: string
            required: true
          - label: userName
            name: userName
            widget: string
            required: true
          - label: userEmail
            name: userEmail
            widget: string
            required: true
          - label: userPhone
            name: userPhone
            widget: string
            required: true
          - label: userTwitter
            name: userTwitter
            widget: string
            required: true
          - label: userLocation
            name: userLocation
            widget: string
            required: true
          - label: userAvatar
            name: userAvatar
            widget: image
            required: true
          - label: Social Links
            name: socialLinks
            required: true
            widget: list
            minimize_collapsed: true
            fields:
              - { label: "name", name: "name", widget: "string" }
              - { label: "link", name: "link", widget: "string" }
              - { label: "icon", name: "icon", widget: "image" }
          - label: Copyright Text
            name: copyright
            widget: string
            required: true
